# pytorch_lightning==1.7.7
seed_everything: 42
trainer:
  accelerator: auto
  devices: 1
  max_epochs: 50
  logger: true
  enable_checkpointing: true
  enable_progress_bar: true
  log_every_n_steps: 50
  precision: 32
  enable_model_summary: true
  callbacks: null
model:
  epochs: 50
  batch_size: 32
  lr: 0.001
  differential_privacy: false
  data_augmentation: false
  epsilon: 50.0
  delta: 1.0e-05
  max_grad_norm: 1.2
